name: JARVIS Android Build

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Test workflow
        run: |
          echo "JARVIS workflow is recognized."
          echo "GitHub Actions is working."
